[[call]]
call_type = "deploy"
class_hash = "0x0222a0fb4bf5695fe80975e37add33aa0d52d21f71b802ebb3e2a3f9d968c1b1"
inputs = []
id = "contract_oods"
unique = false

[[call]]
call_type = "deploy"
class_hash = "0x39c69f3b9aeeed25ee23a137a308e6a91dc0816afba87d485d8f38f9292cfc8"
inputs = ["0", "contract_oods"]
id = "cairo_verifier"
unique = false