[sncast.default]
accounts-file = "~/.starknet_accounts/starknet_open_zeppelin_accounts.json"
account = "DevAccount"
url = "https://starknet-sepolia.g.alchemy.com/starknet/version/rpc/v0_7/ayXO_gsh9HUbBE-Mm9I_HNdGrIPmrgeI"