[[call]]
call_type = "deploy"
class_hash = "0x246bd5f414e2182a56c22a23303db9cb851ec314b9881ae52c19dfca9ed3e1c"
inputs = []
id = "contract_oods"
unique = false

[[call]]
call_type = "deploy"
class_hash = "0x2f88b7853c698bd964bee936fc951d95f14e9025845cbd32493476b5a16fae7"
inputs = ["0", "contract_oods"]
id = "cairo_verifier"
unique = false