[[call]]
call_type = "deploy"
class_hash = "0x5cae9f970c8da62a83193d7faefdeac3b419ff698badd4f5d502d5b11beb74f"
inputs = []
id = "contract_oods"
unique = false

[[call]]
call_type = "deploy"
class_hash = "0x53b659fd4a42151ee331523146f804de0d6466987b73f9087bb427182dcba3d"
inputs = ["0", "contract_oods"]
id = "cairo_verifier"
unique = false