[[call]]
call_type = "deploy"
class_hash = "0x5cae9f970c8da62a83193d7faefdeac3b419ff698badd4f5d502d5b11beb74f"
inputs = []
id = "contract_oods"
unique = false

[[call]]
call_type = "deploy"
class_hash = "0x2f4e4f17af30e615534604c0755d4a2ecd1209b0ded9bfb83b86bb81dd7efe"
inputs = ["0", "contract_oods"]
id = "cairo_verifier"
unique = false