[[call]]
call_type = "deploy"
class_hash = "0x06df5e737f0bd804425b50206f073b5677e236c5e705847c8bbda03eae9824d1"
inputs = []
id = "contract_oods"
unique = false

[[call]]
call_type = "deploy"
class_hash = "0x2625a3ff36886d04eb41cc4d43119adefd2f8c4770c1c7c6ddb9385a788e82f"
inputs = ["0", "contract_oods"]
id = "cairo_verifier"
unique = false