[[call]]
call_type = "deploy"
class_hash = "0x06c41c76977bf08e33624ed3c01e2cc79922671c120af74795b5e2f8633d7a99"
inputs = []
id = "contract_composition"
unique = false

[[call]]
call_type = "deploy"
class_hash = "0x4b8175dfef1d3198d177f8c55bef570615362ab9d1e5179e69b06d6b3aeb0f1"
inputs = ["contract_composition", "0"]
id = "cairo_verifier"
unique = false