[[call]]
call_type = "deploy"
class_hash = "0x416f281795dbcc812a0f23c9082f4a786b47efa66e3d733a72031c7cbb9b5be"
inputs = []
id = "contract_composition"
unique = false

[[call]]
call_type = "deploy"
class_hash = "0x6bdce3b21308b4837db5caaa91bc501eb1a50e0cf5550cbd60ee95bc288d130"
inputs = ["contract_composition", "0"]
id = "cairo_verifier"
unique = false