[[call]]
call_type = "deploy"
class_hash = "0x5cae9f970c8da62a83193d7faefdeac3b419ff698badd4f5d502d5b11beb74f"
inputs = []
id = "contract_oods"
unique = false

[[call]]
call_type = "deploy"
class_hash = "0x62fb4efbda30065e64706029e94a71ad7f28a969c9aea19d3f769e268c01b89"
inputs = ["0", "contract_oods"]
id = "cairo_verifier"
unique = false