[[call]]
call_type = "deploy"
class_hash = "0x05cae9f970c8da62a83193d7faefdeac3b419ff698badd4f5d502d5b11beb74f"
inputs = []
id = "contract_oods"
unique = false

[[call]]
call_type = "deploy"
class_hash = "0x336ded106c6838030eba86d6736bb2c7fbf680ef428d6485de2de674eb5a3b9"
inputs = ["0", "contract_oods"]
id = "cairo_verifier"
unique = false