[[call]]
call_type = "deploy"
class_hash = "0x05cae9f970c8da62a83193d7faefdeac3b419ff698badd4f5d502d5b11beb74f"
inputs = []
id = "contract_oods"
unique = false

[[call]]
call_type = "deploy"
class_hash = "0x8c8f78c23dc076ed1e2211724e7742f6c9e4282d105050d93c4c94c2e9dec7"
inputs = ["0", "contract_oods"]
id = "cairo_verifier"
unique = false