[[call]]
call_type = "deploy"
class_hash = "0x246bd5f414e2182a56c22a23303db9cb851ec314b9881ae52c19dfca9ed3e1c"
inputs = []
id = "contract_oods"
unique = false

[[call]]
call_type = "deploy"
class_hash = "0x44f93c9a340067573fffd5f7ca6110808b13cd3e7027dab824f9c790d38ea83"
inputs = ["0", "contract_oods"]
id = "cairo_verifier"
unique = false