[[call]]
call_type = "deploy"
class_hash = "0x05cae9f970c8da62a83193d7faefdeac3b419ff698badd4f5d502d5b11beb74f"
inputs = []
id = "contract_oods"
unique = false

[[call]]
call_type = "deploy"
class_hash = "0x338e2ab9e0f32f3d46ddc8eddbf022f3d337c9a608d021b7e6439043b4ee41e"
inputs = ["0", "contract_oods"]
id = "cairo_verifier"
unique = false