[[call]]
call_type = "deploy"
class_hash = "0x4b4c16ed4d52624714fb87efe9d420618c5be3ab67fe6f002478e423a4d3984"
inputs = []
id = "contract_composition_1"
unique = false

[[call]]
call_type = "deploy"
class_hash = "0x729a9f54ca7b416d3eac5ccb4ffd43c436b700bf4f4ecd87aafa20034d4f506"
inputs = []
id = "contract_composition_2"
unique = false

[[call]]
call_type = "deploy"
class_hash = "0x66f23f373c9efed0db728c9ac2dcbcea9fa17311249e374bb04e471b9d45b4b"
inputs = []
id = "contract_composition_3"
unique = false

[[call]]
call_type = "deploy"
class_hash = "0x68712d80117620753da7d63dd8dcd83ba1c38a889318f33eada86c3589513e4"
inputs = ["contract_composition_1", "contract_composition_2", "contract_composition_3"]
id = "contract_composition_master"
unique = false

[[call]]
call_type = "deploy"
class_hash = "0x3a1b3aceb40491ea87617f88c26a27657e68720df15b75d6ddd1d0cf90682b2"
inputs = []
id = "contract_oods"
unique = false

[[call]]
call_type = "deploy"
class_hash = "0x48dac1ce3ef2c6af11a1289225a843affa3add513d8b4d7599ca74f527a07bb"
inputs = ["contract_composition_master", "contract_oods"]
id = "cairo_verifier"
unique = false