[[call]]
call_type = "deploy"
class_hash = "0x06c41c76977bf08e33624ed3c01e2cc79922671c120af74795b5e2f8633d7a99"
inputs = []
id = "contract_composition"
unique = false

[[call]]
call_type = "deploy"
class_hash = "0x3b4262853675fd80d71d8860cfb99da12c3a7cb04de780e91a1b7f5d53a682a"
inputs = ["contract_composition", "0"]
id = "cairo_verifier"
unique = false