[[call]]
call_type = "deploy"
class_hash = "0x06c41c76977bf08e33624ed3c01e2cc79922671c120af74795b5e2f8633d7a99"
inputs = []
id = "contract_composition"
unique = false

[[call]]
call_type = "deploy"
class_hash = "0x6f9bc54216975378e0c6a7ca7f8fe6e7f27ed216ef4ff6b86b3bc4d652bfe3e"
inputs = ["contract_composition", "0"]
id = "cairo_verifier"
unique = false