[[call]]
call_type = "deploy"
class_hash = "0x6df5e737f0bd804425b50206f073b5677e236c5e705847c8bbda03eae9824d1"
inputs = []
id = "contract_oods"
unique = false

[[call]]
call_type = "deploy"
class_hash = "0x6cc759c0bce9c1db38bea8ca10f2dd2126f65f40f64167fd4d2ef3488a9ff47"
inputs = ["0", "contract_oods"]
id = "cairo_verifier"
unique = false