[[call]]
call_type = "invoke"
contract_address = "0x038f56b1Cc89F907a5ddD9343b83bd97b85366c86B99F156F5CA28fb6494ba83" # FactRegistry address
function = "register_verifier"
inputs = [
    "REPLACE WITH LAYOUT STRING AS HEX", # layout
    "REPLACE WITH HASHER STRING AS HEX", # hasher
    "50", # security_bits
    "0x73746f6e6535", # version
    "REPLACE WITH VERIFIER CONTRACT ADDRESS", # CairoVerifier address
]