[[call]]
call_type = "deploy"
class_hash = "0x49cc114a5b78d679c970e22b7fd0d6e503b29a7d96aaa3efda46381c36d8407"
inputs = ["REPLACE WITH DEPLOYER ADDRESS"]
unique = true
id = "fact_registry"

# starknet_with_keccak keccak
[[call]]
call_type = "invoke"
contract_address = "fact_registry"
function = "register_verifier"
inputs = [
    "0x737461726b6e65745f776974685f6b656363616b", # layout
    "0x6b656363616b", # hasher
    "50", # security_bits
    "0x73746f6e6535", # version
    "0x0681e6956397919cf1369BFDdDdcDDc4D8FBebC83e12368a4a1Da874F96ff7da", # CairoVerifier address
]

# starknet_with_keccak blake2s
[[call]]
call_type = "invoke"
contract_address = "fact_registry"
function = "register_verifier"
inputs = [
    "0x737461726b6e65745f776974685f6b656363616b", # layout
    "0x626c616b653273", # hasher
    "50", # security_bits
    "0x73746f6e6535", # version
    "0x0736b43951839ba7d9d0c5530e40be41895b6f3a0880fe9f510014203b8b4ee2", # CairoVerifier address
]

# recursive keccak
[[call]]
call_type = "invoke"
contract_address = "fact_registry"
function = "register_verifier"
inputs = [
    "0x726563757273697665", # layout
    "0x6b656363616b", # hasher
    "50", # security_bits
    "0x73746f6e6535", # version
    "0x05a5c2e67772a9339de5aa8245bf7da0d2907e47b6ba228b037e251b64b7c7e6", # CairoVerifier address
]

# recursive blake2s
[[call]]
call_type = "invoke"
contract_address = "fact_registry"
function = "register_verifier"
inputs = [
    "0x726563757273697665", # layout
    "0x626c616b653273", # hasher
    "50", # security_bits
    "0x73746f6e6535", # version
    "0xa10321d430724c6b209f9bd6f4fcd3f649c4f2167dcb852ef598eb92dcbda9", # CairoVerifier address
]

# recursive_with_poseidon keccak
[[call]]
call_type = "invoke"
contract_address = "fact_registry"
function = "register_verifier"
inputs = [
    "0x7265637572736976655f776974685f706f736569646f6e", # layout
    "0x6b656363616b", # hasher
    "50", # security_bits
    "0x73746f6e6535", # version
    "0x028f4624068d909b3e380fd7fcb5326fb666be23ecd224c068bb2c4807e24390", # CairoVerifier address
]

# recursive_with_poseidon blake2s
[[call]]
call_type = "invoke"
contract_address = "fact_registry" # FactRegistry address
function = "register_verifier"
inputs = [
    "0x7265637572736976655f776974685f706f736569646f6e", # layout
    "0x626c616b653273", # hasher
    "50", # security_bits
    "0x73746f6e6535", # version
    "0x041757de95138588678afe5ad14464449430cd6da0fbc522a9334196fd6fb1c1", # CairoVerifier address
]

# dex keccak
[[call]]
call_type = "invoke"
contract_address = "fact_registry" # FactRegistry address
function = "register_verifier"
inputs = [
    "0x646578", # layout
    "0x6b656363616b", # hasher
    "50", # security_bits
    "0x73746f6e6535", # version
    "0x01a12C107F44b1653051cb2Ac93D2706e001403418e640e4a342aCf504f5CF2E", # CairoVerifier address
]

# dex blake2s
[[call]]
call_type = "invoke"
contract_address = "fact_registry" # FactRegistry address
function = "register_verifier"
inputs = [
    "0x646578", # layout
    "0x626c616b653273", # hasher
    "50", # security_bits
    "0x73746f6e6535", # version
    "0x045d9A5B39B732Aeaca40E539a0d58d39122B70a2babd349Fd295E97890d5a75", # CairoVerifier address
]

# small keccak
[[call]]
call_type = "invoke"
contract_address = "fact_registry" # FactRegistry address
function = "register_verifier"
inputs = [
    "0x736d616c6c", # layout
    "0x6b656363616b", # hasher
    "50", # security_bits
    "0x73746f6e6535", # version
    "0x02891972D602fa4f1e7BcC242B335FF7ec2aa428221720a38233184e1129756E", # CairoVerifier address
]

# small blake2s
[[call]]
call_type = "invoke"
contract_address = "fact_registry" # FactRegistry address
function = "register_verifier"
inputs = [
    "0x736d616c6c", # layout
    "0x626c616b653273", # hasher
    "50", # security_bits
    "0x73746f6e6535", # version
    "0x0770C16c93E959089a526194902191807c51c0c498482B777Dd21C27a72FF56b", # CairoVerifier address
]

# starknet keccak
[[call]]
call_type = "invoke"
contract_address = "fact_registry" # FactRegistry address
function = "register_verifier"
inputs = [
    "0x737461726b6e6574", # layout
    "0x6b656363616b", # hasher
    "50", # security_bits
    "0x73746f6e6535", # version
    "0x02fc00e968d3687d62489c1cf32c65caf6764b80441f2c472e4cf37ffdb73900", # CairoVerifier address
]

# starknet blake2s
[[call]]
call_type = "invoke"
contract_address = "fact_registry" # FactRegistry address
function = "register_verifier"
inputs = [
    "0x737461726b6e6574", # layout
    "0x626c616b653273", # hasher
    "50", # security_bits
    "0x73746f6e6535", # version
    "0x03c46D3e21a2DED49Dc19CA23Ea93429Afb0a837a7489dF797440A3c1bfC61D6", # CairoVerifier address
]