use cairo_verifier::air::layouts::starknet_with_keccak::global_values::GlobalValues;


#[starknet::interface]
trait IStarknetWithKeccakLayoutContract1<ContractState> {
    fn eval_composition_polynomial_inner(
        self: @ContractState,
        mask_values: Span<felt252>,
        constraint_coefficients: Span<felt252>,
        point: felt252,
        trace_generator: felt252,
        global_values: GlobalValues
    ) -> felt252;
}

#[starknet::interface]
trait IStarknetWithKeccakLayoutContract2<ContractState> {
    fn eval_oods_polynomial_inner(
        self: @ContractState,
        column_values: Span<felt252>,
        oods_values: Span<felt252>,
        constraint_coefficients: Span<felt252>,
        point: felt252,
        oods_point: felt252,
        trace_generator: felt252,
    ) -> felt252;
}

#[starknet::contract]
mod StarknetWithKeccakLayoutContract1 {
    use cairo_verifier::air::layouts::starknet_with_keccak::contract::IStarknetWithKeccakLayoutContract1DispatcherTrait;
    use super::{IStarknetWithKeccakLayoutContract1, IStarknetWithKeccakLayoutContract1Dispatcher};
    use cairo_verifier::air::layouts::starknet_with_keccak::global_values::GlobalValues;
    use starknet::ContractAddress;

    #[storage]
    struct Storage {
        contracts: LegacyMap::<felt252, ContractAddress>,
        contracts_count: felt252,
    }

    #[constructor]
    fn constructor(ref self: ContractState, contracts: Array<ContractAddress>) {
        let n: felt252 = contracts.len().into();
        self.contracts_count.write(n);
        let mut i = 0;
        loop {
            if i.into() == n {
                break;
            }
            self.contracts.write(i.into(), *contracts.at(i));
            i += 1;
        };
    }

    #[abi(embed_v0)]
    impl StarknetWithKeccakLayoutContract1 of IStarknetWithKeccakLayoutContract1<ContractState> {
        fn eval_composition_polynomial_inner(
            self: @ContractState,
            mask_values: Span<felt252>,
            constraint_coefficients: Span<felt252>,
            point: felt252,
            trace_generator: felt252,
            global_values: GlobalValues
        ) -> felt252 {
            let mut total_sum = 0;
            let mut i: u32 = 0;
            let n: felt252 = self.contracts_count.read().into();
            let begin = array![
                0,
                95,
                195,
                229,
                260,
                285,
                310,
            ].span();
            let length = array![
                95,
                100,
                34,
                31,
                25,
                25,
                37,
            ].span();
            loop {
                if i.into() == n {
                    break total_sum;
                }
                
                let contract = IStarknetWithKeccakLayoutContract1Dispatcher {
                    contract_address: self.contracts.read(i.into())
                };
                let coeffs = constraint_coefficients.slice(*begin.at(i), *length.at(i));
                total_sum += contract.eval_composition_polynomial_inner(mask_values, coeffs, point, trace_generator, global_values);
                i += 1;
            }
        }
    }
}

#[starknet::contract]
mod StarknetWithKeccakLayoutContract1part1 {
    use super::IStarknetWithKeccakLayoutContract1;
    use cairo_verifier::air::layouts::starknet_with_keccak::{
        global_values::GlobalValues,
        autogenerated::eval_composition_polynomial_inner_part1,
    };

    #[storage]
    struct Storage {}

    #[abi(embed_v0)]
    impl StarknetWithKeccakLayoutContract1part1 of IStarknetWithKeccakLayoutContract1<ContractState> {
        fn eval_composition_polynomial_inner(
            self: @ContractState,
            mask_values: Span<felt252>,
            constraint_coefficients: Span<felt252>,
            point: felt252,
            trace_generator: felt252,
            global_values: GlobalValues
        ) -> felt252 {
            eval_composition_polynomial_inner_part1(
                mask_values,
                constraint_coefficients,
                point,
                trace_generator,
                global_values
            )
        }
    }
}

#[starknet::contract]
mod StarknetWithKeccakLayoutContract1part2 {
    use super::IStarknetWithKeccakLayoutContract1;
    use cairo_verifier::air::layouts::starknet_with_keccak::{
        global_values::GlobalValues,
        autogenerated::eval_composition_polynomial_inner_part2,
    };

    #[storage]
    struct Storage {}

    #[abi(embed_v0)]
    impl StarknetWithKeccakLayoutContract1part2 of IStarknetWithKeccakLayoutContract1<ContractState> {
        fn eval_composition_polynomial_inner(
            self: @ContractState,
            mask_values: Span<felt252>,
            constraint_coefficients: Span<felt252>,
            point: felt252,
            trace_generator: felt252,
            global_values: GlobalValues
        ) -> felt252 {
            eval_composition_polynomial_inner_part2(
                mask_values,
                constraint_coefficients,
                point,
                trace_generator,
                global_values
            )
        }
    }
}

#[starknet::contract]
mod StarknetWithKeccakLayoutContract1part3 {
    use super::IStarknetWithKeccakLayoutContract1;
    use cairo_verifier::air::layouts::starknet_with_keccak::{
        global_values::GlobalValues,
        autogenerated::eval_composition_polynomial_inner_part3,
    };

    #[storage]
    struct Storage {}

    #[abi(embed_v0)]
    impl StarknetWithKeccakLayoutContract1part3 of IStarknetWithKeccakLayoutContract1<ContractState> {
        fn eval_composition_polynomial_inner(
            self: @ContractState,
            mask_values: Span<felt252>,
            constraint_coefficients: Span<felt252>,
            point: felt252,
            trace_generator: felt252,
            global_values: GlobalValues
        ) -> felt252 {
            eval_composition_polynomial_inner_part3(
                mask_values,
                constraint_coefficients,
                point,
                trace_generator,
                global_values
            )
        }
    }
}

#[starknet::contract]
mod StarknetWithKeccakLayoutContract1part4 {
    use super::IStarknetWithKeccakLayoutContract1;
    use cairo_verifier::air::layouts::starknet_with_keccak::{
        global_values::GlobalValues,
        autogenerated::eval_composition_polynomial_inner_part4,
    };

    #[storage]
    struct Storage {}

    #[abi(embed_v0)]
    impl StarknetWithKeccakLayoutContract1part4 of IStarknetWithKeccakLayoutContract1<ContractState> {
        fn eval_composition_polynomial_inner(
            self: @ContractState,
            mask_values: Span<felt252>,
            constraint_coefficients: Span<felt252>,
            point: felt252,
            trace_generator: felt252,
            global_values: GlobalValues
        ) -> felt252 {
            eval_composition_polynomial_inner_part4(
                mask_values,
                constraint_coefficients,
                point,
                trace_generator,
                global_values
            )
        }
    }
}

#[starknet::contract]
mod StarknetWithKeccakLayoutContract1part5 {
    use super::IStarknetWithKeccakLayoutContract1;
    use cairo_verifier::air::layouts::starknet_with_keccak::{
        global_values::GlobalValues,
        autogenerated::eval_composition_polynomial_inner_part5,
    };

    #[storage]
    struct Storage {}

    #[abi(embed_v0)]
    impl StarknetWithKeccakLayoutContract1part5 of IStarknetWithKeccakLayoutContract1<ContractState> {
        fn eval_composition_polynomial_inner(
            self: @ContractState,
            mask_values: Span<felt252>,
            constraint_coefficients: Span<felt252>,
            point: felt252,
            trace_generator: felt252,
            global_values: GlobalValues
        ) -> felt252 {
            eval_composition_polynomial_inner_part5(
                mask_values,
                constraint_coefficients,
                point,
                trace_generator,
                global_values
            )
        }
    }
}

#[starknet::contract]
mod StarknetWithKeccakLayoutContract1part6 {
    use super::IStarknetWithKeccakLayoutContract1;
    use cairo_verifier::air::layouts::starknet_with_keccak::{
        global_values::GlobalValues,
        autogenerated::eval_composition_polynomial_inner_part6,
    };

    #[storage]
    struct Storage {}

    #[abi(embed_v0)]
    impl StarknetWithKeccakLayoutContract1part6 of IStarknetWithKeccakLayoutContract1<ContractState> {
        fn eval_composition_polynomial_inner(
            self: @ContractState,
            mask_values: Span<felt252>,
            constraint_coefficients: Span<felt252>,
            point: felt252,
            trace_generator: felt252,
            global_values: GlobalValues
        ) -> felt252 {
            eval_composition_polynomial_inner_part6(
                mask_values,
                constraint_coefficients,
                point,
                trace_generator,
                global_values
            )
        }
    }
}

#[starknet::contract]
mod StarknetWithKeccakLayoutContract1part7 {
    use super::IStarknetWithKeccakLayoutContract1;
    use cairo_verifier::air::layouts::starknet_with_keccak::{
        global_values::GlobalValues,
        autogenerated::eval_composition_polynomial_inner_part7,
    };

    #[storage]
    struct Storage {}

    #[abi(embed_v0)]
    impl StarknetWithKeccakLayoutContract1part7 of IStarknetWithKeccakLayoutContract1<ContractState> {
        fn eval_composition_polynomial_inner(
            self: @ContractState,
            mask_values: Span<felt252>,
            constraint_coefficients: Span<felt252>,
            point: felt252,
            trace_generator: felt252,
            global_values: GlobalValues
        ) -> felt252 {
            eval_composition_polynomial_inner_part7(
                mask_values,
                constraint_coefficients,
                point,
                trace_generator,
                global_values
            )
        }
    }
}

#[starknet::contract]
mod StarknetWithKeccakLayoutContract2part1 {
    use super::IStarknetWithKeccakLayoutContract2;
    use cairo_verifier::air::layouts::starknet_with_keccak::{
        global_values::GlobalValues,
        autogenerated::eval_oods_polynomial_inner_part1,
    };

    #[storage]
    struct Storage {}

    #[abi(embed_v0)]
    impl StarknetWithKeccakLayoutContract2part1 of IStarknetWithKeccakLayoutContract2<ContractState> {
        fn eval_oods_polynomial_inner(
            self: @ContractState,
            column_values: Span<felt252>,
            oods_values: Span<felt252>,
            constraint_coefficients: Span<felt252>,
            point: felt252,
            oods_point: felt252,
            trace_generator: felt252,
        ) -> felt252 {
            eval_oods_polynomial_inner_part1(
                column_values,
                oods_values,
                constraint_coefficients,
                point,
                oods_point,
                trace_generator,
            )
        }
    }
}

#[starknet::contract]
mod StarknetWithKeccakLayoutContract2part2 {
    use super::IStarknetWithKeccakLayoutContract2;
    use cairo_verifier::air::layouts::starknet_with_keccak::{
        global_values::GlobalValues,
        autogenerated::eval_oods_polynomial_inner_part2,
    };

    #[storage]
    struct Storage {}

    #[abi(embed_v0)]
    impl StarknetWithKeccakLayoutContract2part2 of IStarknetWithKeccakLayoutContract2<ContractState> {
        fn eval_oods_polynomial_inner(
            self: @ContractState,
            column_values: Span<felt252>,
            oods_values: Span<felt252>,
            constraint_coefficients: Span<felt252>,
            point: felt252,
            oods_point: felt252,
            trace_generator: felt252,
        ) -> felt252 {
            eval_oods_polynomial_inner_part2(
                column_values,
                oods_values,
                constraint_coefficients,
                point,
                oods_point,
                trace_generator,
            )
        }
    }
}

#[starknet::contract]
mod StarknetWithKeccakLayoutContract2 {
    use super::{IStarknetWithKeccakLayoutContract2, IStarknetWithKeccakLayoutContract2Dispatcher, IStarknetWithKeccakLayoutContract2DispatcherTrait};
    use cairo_verifier::air::layouts::starknet_with_keccak::global_values::GlobalValues;
    use starknet::ContractAddress;

    #[storage]
    struct Storage {
        contract_address_1: ContractAddress,
        contract_address_2: ContractAddress,
    }

    #[constructor]
    fn constructor(ref self: ContractState, contract_address_1: ContractAddress, contract_address_2: ContractAddress) {
        self.contract_address_1.write(contract_address_1);
        self.contract_address_2.write(contract_address_2);
    }

    #[abi(embed_v0)]
    impl StarknetWithKeccakLayoutContract2 of IStarknetWithKeccakLayoutContract2<ContractState> {
        fn eval_oods_polynomial_inner(
            self: @ContractState,
            column_values: Span<felt252>,
            oods_values: Span<felt252>,
            constraint_coefficients: Span<felt252>,
            point: felt252,
            oods_point: felt252,
            trace_generator: felt252,
        ) -> felt252 {
            let coeffs1 = constraint_coefficients.slice(0, 349);
            let coeffs2 = constraint_coefficients.slice(349, constraint_coefficients.len() - 349);
            let oods1 = oods_values.slice(0, 349);
            let oods2 = oods_values.slice(349, oods_values.len() - 349);

            let sum1 = IStarknetWithKeccakLayoutContract2Dispatcher {
                contract_address: self.contract_address_1.read()
            }.eval_oods_polynomial_inner(column_values, oods1, coeffs1, point, oods_point, trace_generator);
            let sum2 = IStarknetWithKeccakLayoutContract2Dispatcher {
                contract_address: self.contract_address_2.read()
            }.eval_oods_polynomial_inner(column_values, oods2, coeffs2, point, oods_point, trace_generator);
            sum1 + sum2
        }
    }
}
