[[call]]
call_type = "deploy"
class_hash = "0x2c4188edbf22556e0d396eb2af100c37628f0b9fc75564af4fe396f385fb1f2"
inputs = []
id = "contract_composition"
unique = false

[[call]]
call_type = "deploy"
class_hash = "0x38b1b31fe2b17b4a1c84e2aad6d982ab33b19083763e7e600484de4e2db4426"
inputs = []
id = "contract_oods"
unique = false

[[call]]
call_type = "deploy"
class_hash = "0x4e238eacb448721bf0e82b564e0f1e011857b2682ffb29fea01b87d93f3291a"
inputs = ["contract_composition", "contract_oods"]
id = "cairo_verifier"
unique = false