[[call]]
call_type = "deploy"
class_hash = "0x222a0fb4bf5695fe80975e37add33aa0d52d21f71b802ebb3e2a3f9d968c1b1"
inputs = []
id = "contract_oods"
unique = false

[[call]]
call_type = "deploy"
class_hash = "0x48e1e2ad0709e4d82bca3aca0f69a73d9e00c00fdc00d6bb46d40bf45fba9f7"
inputs = ["0", "contract_oods"]
id = "cairo_verifier"
unique = false