[[call]]
call_type = "deploy"
class_hash = "0x5c2f89ddea573e4dc49f72efc66ac5edcda96d297aa548012b93134a4d87b9"
inputs = []
id = "contract_oods"
unique = false

[[call]]
call_type = "deploy"
class_hash = "0x1f1051dbdebc1b5d06fdb5ace161462fc30a4d0f4c49cedfd19e4f0edc6aae0"
inputs = ["0", "contract_oods"]
id = "cairo_verifier"
unique = false