[[call]]
call_type = "deploy"
class_hash = "0x222a0fb4bf5695fe80975e37add33aa0d52d21f71b802ebb3e2a3f9d968c1b1"
inputs = []
id = "contract_oods"
unique = false

[[call]]
call_type = "deploy"
class_hash = "0x568ededdacd96311b6a6534c8e36ba8bf1dde0c9e8b55cfc18e780772b852f8"
inputs = ["0", "contract_oods"]
id = "cairo_verifier"
unique = false