const ADD_MOD_BATCH_SIZE: felt252 = 1;
const ADD_MOD_N_WORDS: felt252 = 4;
const ADD_MOD_WORD_BIT_LEN: felt252 = 96;
const BITWISE_TOTAL_N_BITS: felt252 = 251;
const CONSTRAINT_DEGREE: u32 = 2;
const CPU_COMPONENT_HEIGHT: felt252 = 16;
const DILUTED_N_BITS: felt252 = 16;
const DILUTED_SPACING: felt252 = 4;
const EC_OP_N_BITS: felt252 = 252;
const EC_OP_SCALAR_HEIGHT: felt252 = 256;
const ECDSA_BUILTIN_REPETITIONS: felt252 = 1;
const ECDSA_ELEMENT_BITS: felt252 = 251;
const ECDSA_ELEMENT_HEIGHT: felt252 = 256;
const HAS_ADD_MOD_BUILTIN: felt252 = 1;
const HAS_BITWISE_BUILTIN: felt252 = 1;
const HAS_DILUTED_POOL: felt252 = 1;
const HAS_EC_OP_BUILTIN: felt252 = 1;
const HAS_ECDSA_BUILTIN: felt252 = 1;
const HAS_KECCAK_BUILTIN: felt252 = 1;
const HAS_MUL_MOD_BUILTIN: felt252 = 1;
const HAS_OUTPUT_BUILTIN: felt252 = 1;
const HAS_PEDERSEN_BUILTIN: felt252 = 1;
const HAS_POSEIDON_BUILTIN: felt252 = 1;
const HAS_RANGE_CHECK_BUILTIN: felt252 = 1;
const HAS_RANGE_CHECK96_BUILTIN: felt252 = 1;
const IS_DYNAMIC_AIR: felt252 = 1;
const LAYOUT_CODE: felt252 = 0x64796e616d6963;
const MASK_SIZE: u32 = 941;
const MUL_MOD_BATCH_SIZE: felt252 = 1;
const MUL_MOD_N_WORDS: felt252 = 4;
const MUL_MOD_WORD_BIT_LEN: felt252 = 96;
const N_CONSTRAINTS: u32 = 419;
const N_DYNAMIC_PARAMS: felt252 = 340;
const PEDERSEN_BUILTIN_REPETITIONS: felt252 = 1;
const POSEIDON_M: felt252 = 3;
const POSEIDON_ROUNDS_FULL: felt252 = 8;
const POSEIDON_ROUNDS_PARTIAL: felt252 = 83;
const PUBLIC_MEMORY_FRACTION: felt252 = 8;
const RANGE_CHECK_N_PARTS: felt252 = 8;
const RANGE_CHECK96_N_PARTS: felt252 = 6;

#[derive(Drop, Copy, Serde)]
struct DynamicParams {
    add_mod_a0_suboffset: u32,
    add_mod_a1_suboffset: u32,
    add_mod_a2_suboffset: u32,
    add_mod_a3_suboffset: u32,
    add_mod_a_offset_suboffset: u32,
    add_mod_b0_suboffset: u32,
    add_mod_b1_suboffset: u32,
    add_mod_b2_suboffset: u32,
    add_mod_b3_suboffset: u32,
    add_mod_b_offset_suboffset: u32,
    add_mod_c0_suboffset: u32,
    add_mod_c1_suboffset: u32,
    add_mod_c2_suboffset: u32,
    add_mod_c3_suboffset: u32,
    add_mod_c_offset_suboffset: u32,
    add_mod_carry1_bit_column: u32,
    add_mod_carry1_bit_offset: u32,
    add_mod_carry1_sign_column: u32,
    add_mod_carry1_sign_offset: u32,
    add_mod_carry2_bit_column: u32,
    add_mod_carry2_bit_offset: u32,
    add_mod_carry2_sign_column: u32,
    add_mod_carry2_sign_offset: u32,
    add_mod_carry3_bit_column: u32,
    add_mod_carry3_bit_offset: u32,
    add_mod_carry3_sign_column: u32,
    add_mod_carry3_sign_offset: u32,
    add_mod_n_suboffset: u32,
    add_mod_offsets_ptr_suboffset: u32,
    add_mod_p0_suboffset: u32,
    add_mod_p1_suboffset: u32,
    add_mod_p2_suboffset: u32,
    add_mod_p3_suboffset: u32,
    add_mod_row_ratio: u32,
    add_mod_sub_p_bit_column: u32,
    add_mod_sub_p_bit_offset: u32,
    add_mod_values_ptr_suboffset: u32,
    bitwise_diluted_var_pool_suboffset: u32,
    bitwise_row_ratio: u32,
    bitwise_trim_unpacking192_suboffset: u32,
    bitwise_trim_unpacking193_suboffset: u32,
    bitwise_trim_unpacking194_suboffset: u32,
    bitwise_trim_unpacking195_suboffset: u32,
    bitwise_var_pool_suboffset: u32,
    bitwise_x_or_y_suboffset: u32,
    cpu_decode_mem_inst_suboffset: u32,
    cpu_decode_off0_suboffset: u32,
    cpu_decode_off1_suboffset: u32,
    cpu_decode_off2_suboffset: u32,
    cpu_decode_opcode_range_check_column_column: u32,
    cpu_decode_opcode_range_check_column_offset: u32,
    cpu_operands_mem_dst_suboffset: u32,
    cpu_operands_mem_op0_suboffset: u32,
    cpu_operands_mem_op1_suboffset: u32,
    cpu_operands_ops_mul_column: u32,
    cpu_operands_ops_mul_offset: u32,
    cpu_operands_res_column: u32,
    cpu_operands_res_offset: u32,
    cpu_registers_ap_column: u32,
    cpu_registers_ap_offset: u32,
    cpu_registers_fp_column: u32,
    cpu_registers_fp_offset: u32,
    cpu_update_registers_update_pc_tmp0_column: u32,
    cpu_update_registers_update_pc_tmp0_offset: u32,
    cpu_update_registers_update_pc_tmp1_column: u32,
    cpu_update_registers_update_pc_tmp1_offset: u32,
    cpu_component_step: u32,
    diluted_check_cumulative_value_column: u32,
    diluted_check_cumulative_value_offset: u32,
    diluted_check_permutation_cum_prod0_column: u32,
    diluted_check_permutation_cum_prod0_offset: u32,
    diluted_check_permuted_values_column: u32,
    diluted_check_permuted_values_offset: u32,
    diluted_pool_column: u32,
    diluted_pool_offset: u32,
    diluted_units_row_ratio: u32,
    ec_op_doubled_points_x_column: u32,
    ec_op_doubled_points_x_offset: u32,
    ec_op_doubled_points_y_column: u32,
    ec_op_doubled_points_y_offset: u32,
    ec_op_doubling_slope_column: u32,
    ec_op_doubling_slope_offset: u32,
    ec_op_ec_subset_sum_bit_unpacking_prod_ones192_column: u32,
    ec_op_ec_subset_sum_bit_unpacking_prod_ones192_offset: u32,
    ec_op_ec_subset_sum_bit_unpacking_prod_ones196_column: u32,
    ec_op_ec_subset_sum_bit_unpacking_prod_ones196_offset: u32,
    ec_op_ec_subset_sum_partial_sum_x_column: u32,
    ec_op_ec_subset_sum_partial_sum_x_offset: u32,
    ec_op_ec_subset_sum_partial_sum_y_column: u32,
    ec_op_ec_subset_sum_partial_sum_y_offset: u32,
    ec_op_ec_subset_sum_selector_column: u32,
    ec_op_ec_subset_sum_selector_offset: u32,
    ec_op_ec_subset_sum_slope_column: u32,
    ec_op_ec_subset_sum_slope_offset: u32,
    ec_op_ec_subset_sum_x_diff_inv_column: u32,
    ec_op_ec_subset_sum_x_diff_inv_offset: u32,
    ec_op_m_suboffset: u32,
    ec_op_p_x_suboffset: u32,
    ec_op_p_y_suboffset: u32,
    ec_op_q_x_suboffset: u32,
    ec_op_q_y_suboffset: u32,
    ec_op_r_x_suboffset: u32,
    ec_op_r_y_suboffset: u32,
    ec_op_builtin_row_ratio: u32,
    ecdsa_message_suboffset: u32,
    ecdsa_pubkey_suboffset: u32,
    ecdsa_signature0_add_results_inv_column: u32,
    ecdsa_signature0_add_results_inv_offset: u32,
    ecdsa_signature0_add_results_slope_column: u32,
    ecdsa_signature0_add_results_slope_offset: u32,
    ecdsa_signature0_doubling_slope_column: u32,
    ecdsa_signature0_doubling_slope_offset: u32,
    ecdsa_signature0_exponentiate_generator_partial_sum_x_column: u32,
    ecdsa_signature0_exponentiate_generator_partial_sum_x_offset: u32,
    ecdsa_signature0_exponentiate_generator_partial_sum_y_column: u32,
    ecdsa_signature0_exponentiate_generator_partial_sum_y_offset: u32,
    ecdsa_signature0_exponentiate_generator_selector_column: u32,
    ecdsa_signature0_exponentiate_generator_selector_offset: u32,
    ecdsa_signature0_exponentiate_generator_slope_column: u32,
    ecdsa_signature0_exponentiate_generator_slope_offset: u32,
    ecdsa_signature0_exponentiate_generator_x_diff_inv_column: u32,
    ecdsa_signature0_exponentiate_generator_x_diff_inv_offset: u32,
    ecdsa_signature0_exponentiate_key_partial_sum_x_column: u32,
    ecdsa_signature0_exponentiate_key_partial_sum_x_offset: u32,
    ecdsa_signature0_exponentiate_key_partial_sum_y_column: u32,
    ecdsa_signature0_exponentiate_key_partial_sum_y_offset: u32,
    ecdsa_signature0_exponentiate_key_selector_column: u32,
    ecdsa_signature0_exponentiate_key_selector_offset: u32,
    ecdsa_signature0_exponentiate_key_slope_column: u32,
    ecdsa_signature0_exponentiate_key_slope_offset: u32,
    ecdsa_signature0_exponentiate_key_x_diff_inv_column: u32,
    ecdsa_signature0_exponentiate_key_x_diff_inv_offset: u32,
    ecdsa_signature0_extract_r_inv_column: u32,
    ecdsa_signature0_extract_r_inv_offset: u32,
    ecdsa_signature0_extract_r_slope_column: u32,
    ecdsa_signature0_extract_r_slope_offset: u32,
    ecdsa_signature0_key_points_x_column: u32,
    ecdsa_signature0_key_points_x_offset: u32,
    ecdsa_signature0_key_points_y_column: u32,
    ecdsa_signature0_key_points_y_offset: u32,
    ecdsa_signature0_q_x_squared_column: u32,
    ecdsa_signature0_q_x_squared_offset: u32,
    ecdsa_signature0_r_w_inv_column: u32,
    ecdsa_signature0_r_w_inv_offset: u32,
    ecdsa_signature0_z_inv_column: u32,
    ecdsa_signature0_z_inv_offset: u32,
    ecdsa_builtin_row_ratio: u32,
    keccak_input_output_suboffset: u32,
    keccak_keccak_diluted_column0_suboffset: u32,
    keccak_keccak_diluted_column1_suboffset: u32,
    keccak_keccak_diluted_column2_suboffset: u32,
    keccak_keccak_diluted_column3_suboffset: u32,
    keccak_keccak_parse_to_diluted_cumulative_sum_column: u32,
    keccak_keccak_parse_to_diluted_cumulative_sum_offset: u32,
    keccak_keccak_parse_to_diluted_final_reshaped_input_column: u32,
    keccak_keccak_parse_to_diluted_final_reshaped_input_offset: u32,
    keccak_keccak_parse_to_diluted_reshaped_intermediate_column: u32,
    keccak_keccak_parse_to_diluted_reshaped_intermediate_offset: u32,
    keccak_keccak_rotated_parity0_column: u32,
    keccak_keccak_rotated_parity0_offset: u32,
    keccak_keccak_rotated_parity1_column: u32,
    keccak_keccak_rotated_parity1_offset: u32,
    keccak_keccak_rotated_parity2_column: u32,
    keccak_keccak_rotated_parity2_offset: u32,
    keccak_keccak_rotated_parity3_column: u32,
    keccak_keccak_rotated_parity3_offset: u32,
    keccak_keccak_rotated_parity4_column: u32,
    keccak_keccak_rotated_parity4_offset: u32,
    keccak_row_ratio: u32,
    mem_pool_addr_column: u32,
    mem_pool_addr_offset: u32,
    mem_pool_value_column: u32,
    mem_pool_value_offset: u32,
    memory_multi_column_perm_perm_cum_prod0_column: u32,
    memory_multi_column_perm_perm_cum_prod0_offset: u32,
    memory_sorted_addr_column: u32,
    memory_sorted_addr_offset: u32,
    memory_sorted_value_column: u32,
    memory_sorted_value_offset: u32,
    memory_units_row_ratio: u32,
    mul_mod_a0_suboffset: u32,
    mul_mod_a1_suboffset: u32,
    mul_mod_a2_suboffset: u32,
    mul_mod_a3_suboffset: u32,
    mul_mod_a_offset_suboffset: u32,
    mul_mod_b0_suboffset: u32,
    mul_mod_b1_suboffset: u32,
    mul_mod_b2_suboffset: u32,
    mul_mod_b3_suboffset: u32,
    mul_mod_b_offset_suboffset: u32,
    mul_mod_c0_suboffset: u32,
    mul_mod_c1_suboffset: u32,
    mul_mod_c2_suboffset: u32,
    mul_mod_c3_suboffset: u32,
    mul_mod_c_offset_suboffset: u32,
    mul_mod_carry0_part0_suboffset: u32,
    mul_mod_carry0_part1_suboffset: u32,
    mul_mod_carry0_part2_suboffset: u32,
    mul_mod_carry0_part3_suboffset: u32,
    mul_mod_carry0_part4_suboffset: u32,
    mul_mod_carry0_part5_suboffset: u32,
    mul_mod_carry0_part6_suboffset: u32,
    mul_mod_carry1_part0_suboffset: u32,
    mul_mod_carry1_part1_suboffset: u32,
    mul_mod_carry1_part2_suboffset: u32,
    mul_mod_carry1_part3_suboffset: u32,
    mul_mod_carry1_part4_suboffset: u32,
    mul_mod_carry1_part5_suboffset: u32,
    mul_mod_carry1_part6_suboffset: u32,
    mul_mod_carry2_part0_suboffset: u32,
    mul_mod_carry2_part1_suboffset: u32,
    mul_mod_carry2_part2_suboffset: u32,
    mul_mod_carry2_part3_suboffset: u32,
    mul_mod_carry2_part4_suboffset: u32,
    mul_mod_carry2_part5_suboffset: u32,
    mul_mod_carry2_part6_suboffset: u32,
    mul_mod_carry3_part0_suboffset: u32,
    mul_mod_carry3_part1_suboffset: u32,
    mul_mod_carry3_part2_suboffset: u32,
    mul_mod_carry3_part3_suboffset: u32,
    mul_mod_carry3_part4_suboffset: u32,
    mul_mod_carry3_part5_suboffset: u32,
    mul_mod_carry3_part6_suboffset: u32,
    mul_mod_carry4_part0_suboffset: u32,
    mul_mod_carry4_part1_suboffset: u32,
    mul_mod_carry4_part2_suboffset: u32,
    mul_mod_carry4_part3_suboffset: u32,
    mul_mod_carry4_part4_suboffset: u32,
    mul_mod_carry4_part5_suboffset: u32,
    mul_mod_carry4_part6_suboffset: u32,
    mul_mod_carry5_part0_suboffset: u32,
    mul_mod_carry5_part1_suboffset: u32,
    mul_mod_carry5_part2_suboffset: u32,
    mul_mod_carry5_part3_suboffset: u32,
    mul_mod_carry5_part4_suboffset: u32,
    mul_mod_carry5_part5_suboffset: u32,
    mul_mod_carry5_part6_suboffset: u32,
    mul_mod_n_suboffset: u32,
    mul_mod_offsets_ptr_suboffset: u32,
    mul_mod_p0_suboffset: u32,
    mul_mod_p1_suboffset: u32,
    mul_mod_p2_suboffset: u32,
    mul_mod_p3_suboffset: u32,
    mul_mod_p_multiplier0_part0_suboffset: u32,
    mul_mod_p_multiplier0_part1_suboffset: u32,
    mul_mod_p_multiplier0_part2_suboffset: u32,
    mul_mod_p_multiplier0_part3_suboffset: u32,
    mul_mod_p_multiplier0_part4_suboffset: u32,
    mul_mod_p_multiplier0_part5_suboffset: u32,
    mul_mod_p_multiplier1_part0_suboffset: u32,
    mul_mod_p_multiplier1_part1_suboffset: u32,
    mul_mod_p_multiplier1_part2_suboffset: u32,
    mul_mod_p_multiplier1_part3_suboffset: u32,
    mul_mod_p_multiplier1_part4_suboffset: u32,
    mul_mod_p_multiplier1_part5_suboffset: u32,
    mul_mod_p_multiplier2_part0_suboffset: u32,
    mul_mod_p_multiplier2_part1_suboffset: u32,
    mul_mod_p_multiplier2_part2_suboffset: u32,
    mul_mod_p_multiplier2_part3_suboffset: u32,
    mul_mod_p_multiplier2_part4_suboffset: u32,
    mul_mod_p_multiplier2_part5_suboffset: u32,
    mul_mod_p_multiplier3_part0_suboffset: u32,
    mul_mod_p_multiplier3_part1_suboffset: u32,
    mul_mod_p_multiplier3_part2_suboffset: u32,
    mul_mod_p_multiplier3_part3_suboffset: u32,
    mul_mod_p_multiplier3_part4_suboffset: u32,
    mul_mod_p_multiplier3_part5_suboffset: u32,
    mul_mod_row_ratio: u32,
    mul_mod_values_ptr_suboffset: u32,
    num_columns_first: u32,
    num_columns_second: u32,
    orig_public_memory_suboffset: u32,
    pedersen_hash0_ec_subset_sum_bit_unpacking_prod_ones192_column: u32,
    pedersen_hash0_ec_subset_sum_bit_unpacking_prod_ones192_offset: u32,
    pedersen_hash0_ec_subset_sum_bit_unpacking_prod_ones196_column: u32,
    pedersen_hash0_ec_subset_sum_bit_unpacking_prod_ones196_offset: u32,
    pedersen_hash0_ec_subset_sum_partial_sum_x_column: u32,
    pedersen_hash0_ec_subset_sum_partial_sum_x_offset: u32,
    pedersen_hash0_ec_subset_sum_partial_sum_y_column: u32,
    pedersen_hash0_ec_subset_sum_partial_sum_y_offset: u32,
    pedersen_hash0_ec_subset_sum_selector_column: u32,
    pedersen_hash0_ec_subset_sum_selector_offset: u32,
    pedersen_hash0_ec_subset_sum_slope_column: u32,
    pedersen_hash0_ec_subset_sum_slope_offset: u32,
    pedersen_input0_suboffset: u32,
    pedersen_input1_suboffset: u32,
    pedersen_output_suboffset: u32,
    pedersen_builtin_row_ratio: u32,
    poseidon_param_0_input_output_suboffset: u32,
    poseidon_param_1_input_output_suboffset: u32,
    poseidon_param_2_input_output_suboffset: u32,
    poseidon_poseidon_full_rounds_state0_column: u32,
    poseidon_poseidon_full_rounds_state0_offset: u32,
    poseidon_poseidon_full_rounds_state0_squared_column: u32,
    poseidon_poseidon_full_rounds_state0_squared_offset: u32,
    poseidon_poseidon_full_rounds_state1_column: u32,
    poseidon_poseidon_full_rounds_state1_offset: u32,
    poseidon_poseidon_full_rounds_state1_squared_column: u32,
    poseidon_poseidon_full_rounds_state1_squared_offset: u32,
    poseidon_poseidon_full_rounds_state2_column: u32,
    poseidon_poseidon_full_rounds_state2_offset: u32,
    poseidon_poseidon_full_rounds_state2_squared_column: u32,
    poseidon_poseidon_full_rounds_state2_squared_offset: u32,
    poseidon_poseidon_partial_rounds_state0_column: u32,
    poseidon_poseidon_partial_rounds_state0_offset: u32,
    poseidon_poseidon_partial_rounds_state0_squared_column: u32,
    poseidon_poseidon_partial_rounds_state0_squared_offset: u32,
    poseidon_poseidon_partial_rounds_state1_column: u32,
    poseidon_poseidon_partial_rounds_state1_offset: u32,
    poseidon_poseidon_partial_rounds_state1_squared_column: u32,
    poseidon_poseidon_partial_rounds_state1_squared_offset: u32,
    poseidon_row_ratio: u32,
    range_check16_perm_cum_prod0_column: u32,
    range_check16_perm_cum_prod0_offset: u32,
    range_check16_sorted_column: u32,
    range_check16_sorted_offset: u32,
    range_check16_pool_column: u32,
    range_check16_pool_offset: u32,
    range_check96_builtin_inner_range_check0_suboffset: u32,
    range_check96_builtin_inner_range_check1_suboffset: u32,
    range_check96_builtin_inner_range_check2_suboffset: u32,
    range_check96_builtin_inner_range_check3_suboffset: u32,
    range_check96_builtin_inner_range_check4_suboffset: u32,
    range_check96_builtin_inner_range_check5_suboffset: u32,
    range_check96_builtin_mem_suboffset: u32,
    range_check96_builtin_row_ratio: u32,
    range_check_builtin_inner_range_check_suboffset: u32,
    range_check_builtin_mem_suboffset: u32,
    range_check_builtin_row_ratio: u32,
    range_check_units_row_ratio: u32,
    uses_add_mod_builtin: u32,
    uses_bitwise_builtin: u32,
    uses_ec_op_builtin: u32,
    uses_ecdsa_builtin: u32,
    uses_keccak_builtin: u32,
    uses_mul_mod_builtin: u32,
    uses_pedersen_builtin: u32,
    uses_poseidon_builtin: u32,
    uses_range_check96_builtin: u32,
    uses_range_check_builtin: u32,
}

mod segments {
    const ADD_MOD: usize = 11;
    const BITWISE: usize = 6;
    const EC_OP: usize = 7;
    const ECDSA: usize = 5;
    const EXECUTION: usize = 1;
    const KECCAK: usize = 8;
    const MUL_MOD: usize = 12;
    const N_SEGMENTS: usize = 13;
    const OUTPUT: usize = 2;
    const PEDERSEN: usize = 3;
    const POSEIDON: usize = 9;
    const PROGRAM: usize = 0;
    const RANGE_CHECK: usize = 4;
    const RANGE_CHECK96: usize = 10;
}

fn get_builtins() -> Array<felt252> {
    array![
        'output',
        'pedersen',
        'range_check',
        'ecdsa',
        'bitwise',
        'ec_op',
        'keccak',
        'poseidon',
        'range_check96',
        'add_mod',
        'mul_mod'
    ]
}
