name: Continuous Integration - tests

on:
  push:
  pull_request:

jobs:
  verifier-formatting-and-testing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Setup Scarb
        uses: software-mansion/setup-scarb@v1
      
      - name: Format code
        run: scarb fmt --check
      
      - name: Run tests
        run: scarb test

  fact-registry-formatting-and-testing:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout repository
          uses: actions/checkout@v3
      
        - name: Setup Scarb
          uses: software-mansion/setup-scarb@v1

        - name: Setup Starknet Foundry
          uses: foundry-rs/setup-snfoundry@v3
        
        - name: Format code
          run: cd fact_registry && scarb fmt --check
        
        - name: Run tests
          run: cd fact_registry && scarb test