name: Continuous Integration - tests

on:
  push:
  pull_request:

jobs:
  formatting-and-testing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Setup Scarb
        uses: software-mansion/setup-scarb@v1
      
      - name: Format code
        run: scarb fmt --check
      
      - name: Run tests
        run: scarb test
