[[call]]
call_type = "deploy"
class_hash = "0x5c2f89ddea573e4dc49f72efc66ac5edcda96d297aa548012b93134a4d87b9"
inputs = []
id = "contract_oods"
unique = false

[[call]]
call_type = "deploy"
class_hash = "0x44b1de324297d13a4ccc40249e512a2e6289f0b230681cdb66b24a8119263a5"
inputs = ["0", "contract_oods"]
id = "cairo_verifier"
unique = false