[[call]]
call_type = "deploy"
class_hash = "0x0222a0fb4bf5695fe80975e37add33aa0d52d21f71b802ebb3e2a3f9d968c1b1"
inputs = []
id = "contract_oods"
unique = false

[[call]]
call_type = "deploy"
class_hash = "0x380d3fc5a62543cb8647ed40bc46f8b5965343f9514f5ec4b43d7dec4f709f0"
inputs = ["0", "contract_oods"]
id = "cairo_verifier"
unique = false