[[call]]
call_type = "deploy"
class_hash = "0x0222a0fb4bf5695fe80975e37add33aa0d52d21f71b802ebb3e2a3f9d968c1b1"
inputs = []
id = "contract_oods"
unique = false

[[call]]
call_type = "deploy"
class_hash = "0x6f88d24fbdbac3934dbec3583500b67f98eba59e1bb92600d85aa31dadabb9e"
inputs = ["0", "contract_oods"]
id = "cairo_verifier"
unique = false